# Generated by Django 5.1.6 on 2025-02-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot_deal',
            field=models.BooleanField(default=True, verbose_name='Hot Deal!'),
        ),
    ]
