# Generated by Django 5.1.6 on 2025-02-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_is_hot_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/good_images', verbose_name='Изображение товара'),
        ),
    ]
