# Generated by Django 5.1.6 on 2025-02-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_hot_category',
            field=models.BooleanField(default=True, verbose_name='Hot Category!'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/good_images', verbose_name='Изображение товара'),
        ),
    ]
