# Generated by Django 5.1.6 on 2025-02-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_categories_is_hot_category_alter_product_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='popular_category',
            field=models.BooleanField(default=True, verbose_name='Popular Category!'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Название'),
        ),
    ]
