# Generated by Django 5.1.6 on 2025-02-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_categories_popular_category_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/category_images', verbose_name='Изображение Категории'),
        ),
    ]
